services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prosallo
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d prosallo" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4.4
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
